[package]
name = "font-kerning"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
imageproc = "0.22"
rusttype = "0.9.2"
fontdue = "0.6.2"
ab_glyph = "0.2.12"
conv = "0.3.3"
